name: event_navigation
description: Uses the event_bloc package to create a solution for navigation.
version: 0.6.0
homepage: https://github.com/VHCBlade/event-navigation

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  event_bloc: ^4.2.0
  equatable: ^2.0.0
  provider: ^6.0.0
  universal_html: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
